- name: Demo on using variables  
  hosts: all                   
  vars: 
    URL: play.google.com                    # Global Variable; All tasks can inherit this value  
  tasks:
    - name: Printing the URL Task  
      ansible.builtin.debug:
         msg: The value of url is {{URL}}  