- name: Demo on using variables  
  hosts: all                   
  vars_files: demo-vars.yaml
  vars_prompt: 
    - name: PURL  
      prompt: Enter the purl 
      private: true
  vars: 
    URL: play.google.com                    # Global Variable; All tasks can inherit this value  
  tasks:
    - name: Printing the URL Task  
      ansible.builtin.debug:
         msg: The value of url is {{URL}}  